### ISSUE TITLE
pumpkin overlay get removed after a headshot

### ISSUE THREAD

**Issue by darktubeNL** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#13]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

when you get shot to the head while scoping (have the pumpkin overlay) the overlay gets removed?

### Expected Behavior

not remove the overlay?!

### Steps To Reproduce

go scope
get shot in the head

### Frequency

100%

### Version and Log

no

**Comment by DeeCaaD** [comment]
I assume this happens because of durability loss updates the item. Simple fix for this would be to resend the pumpkin on damage

**Comment by CJCrafter** [comment]
fixed in v1.2.2
