### ISSUE TITLE
Hitmarker CQB Bug

### ISSUE THREAD

**Issue by Nightshade73** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#24]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

When in Close Quarters Combat with an enemy, the hitmarker indicators being armor stand based, block right click interaction canceling your weapon from firing. Video: [https://youtu.be/ylMvi7Iwt4Q](url)

### Expected Behavior

Close Quarters should not prevent combat.

### Steps To Reproduce

Enable hitmarkers and be within interaction distance while using Right click shoot.

### Frequency

100%

### Version and Log

![2023-01-11_15 25 25](https://user-images.githubusercontent.com/23036913/211921201-88e51ef3-331c-43c3-be94-9e21e93ded56.png)

[latest.log](https://github.com/WeaponMechanics/WeaponMechanicsCosmeticsWiki/files/10396081/latest.log)

**Comment by CJCrafter** [comment]
Duplicate: https://github.com/WeaponMechanics/MechanicsMain/issues/124
