### ISSUE TITLE
The hand skin will not disappear when I selected to another item.

### ISSUE THREAD

**Issue by O-FLOYER** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#28]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

If I use my weapon and then my left-hand will spawn to my left-hand, right?. So when I scroll-down my mouse to use another item in my hotbar. The main item in my right-hand has been changed but the left hand still there. That left-hand will always disappear when I selected the third item in my hotbar (Including the first item. I mean the weapon item). 

### Expected Behavior

Just a bug

### Steps To Reproduce

Sorry, I don't know what is this mean

### Frequency

100%

### Version and Log

No error in my console. 

### Anything else?

I love everything of WMC

**Comment by CJCrafter** [comment]
fixed in 2.0.2
