### ISSUE TITLE
Task #82

### ISSUE THREAD

**Issue by minercract** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#38]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

The guns when fired in other players causes these errors in console.

### Expected Behavior

Please let me know how to fix it. Or if there's just something wrong with my setup, let me know so I can prevent it from happening again.

### Steps To Reproduce

just shoot players with it

### Frequency

100% but I just noticed it now when it lagged the server. Probably with too much console errors.

### Version and Log

![image](https://github.com/WeaponMechanics/WeaponMechanicsCosmeticsWiki/assets/81936285/b6f9b65b-8b08-4b7a-ba2e-ed676ddddc9a)

### Anything else?

The latest log file cannot be uploaded due to file size but please let me know other ways i can send it. thanks.

**Comment by CJCrafter** [comment]
Please join our discord for support... but 99% sure it is your server version... update server to latest 1.20 (latest 1.20.1 would definitely be preferred)
