### ISSUE TITLE
Show_Time action bar problem while reloding a full weapon

### ISSUE THREAD

**Issue by Herobrine15432** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#7]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

 If you reload a full weapon and you have the Show_Time enabled with action bar in reload, the action bar will sometimes stay locked ad 0.1 seconds

### Expected Behavior

Action bar shouldn't lock at 0.1

### Steps To Reproduce

Explained

### Frequency

90%

### Version and Log

![image](https://user-images.githubusercontent.com/79306926/189978409-a0960a20-a4c7-4d89-836d-ca09f5ce23bf.png)

- Nothing in logs

**Comment by DeeCaaD** [comment]
https://github.com/WeaponMechanics/MechanicsMain/blob/master/WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/weapon/reload/ReloadHandler.java#L192

Here as reminder for me

**Comment by DeeCaaD** [comment]
Fixed https://github.com/WeaponMechanics/MechanicsMain/commit/515f8f7522e7af63a1762e59c473f05e3348fa6b
