### ISSUE TITLE
Crossbow model

### ISSUE THREAD

**Issue by MelonHell** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#8]
### Description

The crossbow has a special model in the hands, ideal for weapons. If you specify `Type: "CROSSBOW"` then this will not work correctly.

- autoshoot not working
- crossbow reloads on the right mouse button
- crossbow shoots arrows

it would be nice to:
- working autoshooting
- if `Type: "CROSSBOW"` then the crossbow is always charged (you can use an empty projectile)

**Comment by CJCrafter** [comment]
Working on this soon since we are now using ProtocolLib in the base plugin

**Comment by CJCrafter** [comment]
Added
